micronaut:
  application:
    name: app
  security:
    authentication: idtoken # <1>
    oauth2:
      clients:
        auth0: # <2>
          client-id: '${OAUTH_CLIENT_ID}' # <3>
          client-secret: '${OAUTH_CLIENT_SECRET}' # <4>
          openid:
            issuer: 'https://${OAUTH_DOMAIN}/' # <5>
    endpoints:
      logout:
        get-allowed: true # <6>
#end::oauth2[]
