micronaut:
  application:
    name: app
  security:
    authentication: idtoken
    oauth2:
      clients:
        auth0:
          client-id: '${OAUTH_CLIENT_ID}'
          client-secret: '${OAUTH_CLIENT_SECRET}'
          openid:
            issuer: 'https://${OAUTH_DOMAIN}/'
    endpoints:
      logout:
        get-allowed: true

