name: Dependency submission
on:
  schedule:
    - cron: '30 0 * * *'
  workflow_dispatch:
jobs:
  update:
    name: Updates Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Setup Gradle to generate and submit dependency graphs
        uses: gradle/gradle-build-action@v2
        with:
          dependency-graph: generate-and-submit
      - name: Run a build, generating the dependency graph snapshot which will be submitted
        run: ./gradlew assemble
#      - name: Gradle Dependency Submission
#        uses: mikepenz/gradle-dependency-submission@v0.9.0

