name: Dependency submission
on:
  schedule:
    - cron: '30 0 * * *'
  workflow_dispatch:
jobs:
  update:
    name: Updates Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Gradle Dependency Submission
        uses: mikepenz/gradle-dependency-submission@v0.9.0

