name: Dependency
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  dependency-submission:
    name: Dependency Submission
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Gradle Dependency Submission
        uses: mikepenz/gradle-dependency-submission@v0.8.6
