name: Tests
on:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew check
        env:
          OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
          OAUTH_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
          OAUTH_DOMAIN: ${{ secrets.OAUTH_DOMAIN }}
  e2e:
    name: e2e
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Gradle build
        run: ./gradlew assemble
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm i && npm run e2e-ci
        env:
          OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
          OAUTH_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
          OAUTH_DOMAIN: ${{ secrets.OAUTH_DOMAIN }}
          CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}

