name: Tests
on:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew check
        env:
          OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
          OAUTH_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
          OAUTH_DOMAIN: ${{ secrets.OAUTH_DOMAIN }}
