name: Update Micronaut
on:
  schedule:
    - cron: '30 0 * * *'
  workflow_dispatch:
jobs:
  update:
    name: Updates Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch Micronaut Maven descriptor
        run: curl https://repo1.maven.org/maven2/io/micronaut/micronaut-core/maven-metadata.xml -o /tmp/micronaut-maven-descriptor.xml
      - name: Extract the latest version
        uses: QwerMike/xpath-action@v1
        id: xpath
        with:
          filename: '/tmp/micronaut-maven-descriptor.xml'
          expression: '/metadata/versioning/latest/text()'
      - name: Upgrade Micronaut Version Number
        run: |
          sed -i 's/micronautVersion.*/micronautVersion=${{ steps.xpath.outputs.result }}/' gradle.properties
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Testing build
        run: ./gradlew assemble --stacktrace
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Upgraded to Micronaut ${{ steps.xpath.outputs.result }}
          title: '[Upgrade] Upgraded to Micronaut ${{ steps.xpath.outputs.result }}'
          body: |
            There is a newer version ${{ steps.xpath.outputs.result }} of Micronaut available. The dependency has been updated and the inspection tools
            have been regenerated.
          labels: chore,upgrade
          assignees: adrienpessu
          branch: upgrade/micronaut
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
      - name: Enable Automerge
        run: gh pr merge --auto --merge "$PR_URL" | echo 0
        env:
          PR_URL: ${{ steps.cpr.outputs.pull-request-url }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
